### ISSUE TITLE
package throwing warning

### ISSUE THREAD

**Issue by nickreich** [nickreich/coarseDataTools#44]
See documentation issue here https://cran.r-project.org/web/checks/check_results_coarseDataTools.html

**Comment by nickreich** [comment]
@scottyaz can you fix the issues with the cd.fit documentation. We are getting this message, from CRAN. I think this is quick and easy stuff to tackle. I've addressed some of the issues with the NAMESPACE file that are also throwing "NOTES" when checking. Am hoping to submit a new version to CRAN in the next week or so:

```
Version: 0.6-2 
Check: for missing documentation entries 
Result: WARN 
    Undocumented S4 methods:
     generic 'plot' and siglist 'cd.fit,ANY'
    All user-level objects in a package (including S4 classes and methods)
    should have documentation entries.
    See chapter ‘Writing R documentation files’ in the ‘Writing R
    Extensions’ manual. 
```

**Comment by scottyaz** [comment]
Sure, I'll have a look this week.

**Comment by nickreich** [comment]
Thanks!

**Comment by nickreich** [comment]
pinging again on this, as I'd like to be able to submit this to CRAN on Friday (they imposed a deadline).

**Comment by scottyaz** [comment]
trying to figure this out now and realized that I was also trying to solve this in 2013 --> http://stackoverflow.com/questions/7356120/how-to-properly-document-s4-methods-using-roxygen2

**Comment by nickreich** [comment]
So, no luck with a solution? Are there any other packages that we could look to for an example?
