### ISSUE TITLE
Request to pull the hackout 3 branch into master

### ISSUE THREAD

**Issue by zkamvar** [nickreich/coarseDataTools#49]
Hello,

We currently have a package [earlyR](https://github.com/reconhub/earlyR), which relies on [EpiEstim version 2](https://github.com/annecori/EpiEstim/tree/new-version), which relies on the [hackout3 branch of this repository](https://github.com/nickreich/coarseDataTools/tree/hackout3).

**Comment by zkamvar** [comment]
Ugh, hit the enter button to early...

Would it be possible to merge the hackout3 branch into master and make a new release on CRAN? I just checked the R CMD check with R 3.6, and it only gives a single warning of a mis-matched argument with the documentation and code, so it's not too difficult to patch.

**Comment by zkamvar** [comment]
Note that I am happy to help out with any of the fiddly bits of getting R CMD check to pass if it will make submission to CRAN happen sooner.

**Comment by nickreich** [comment]
I'd be happy to update this package, would definitely help speed it up to have you manage the "fiddly bits" so that it's ready to submit to cran.
